### ISSUE TITLE
Steam Login does not work

### ISSUE THREAD

**Issue by marcschuler** [bdefore/protondb-data#38]
After trying to log in via steam, this error message is shown.

`{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"BadRequest: invalid expression","trace":["Runtime.UnhandledPromiseRejection: BadRequest: invalid expression","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}`

**Comment by bdefore** [comment]
There's been some work on this the last few months. Is this still an issue for you @marcschuler ?
