### ISSUE TITLE
Website: Cannot sign in

### ISSUE THREAD

**Issue by jmbreuer** [bdefore/protondb-data#42]
When clicking the "Sign in with Steam" button on https://www.protondb.com/profile I'm redirected to a plain text error page:

https://www.protondb.com/.netlify/functions/auth/steam

``` json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'express'\nRequire stack:\n- /var/task/netlify/functions/auth/auth.js\n- /var/task/auth.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'express'",
    "Require stack:",
    "- /var/task/netlify/functions/auth/auth.js",
    "- /var/task/auth.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```
_(prettified for readability)_

I believe this to be a server-side issue; I get exactly the same error with both LibreWolf 97.0.2-1 and Vivaldi 5.1.2567.57 (both gentoo Linux 64-bit).

**Comment by bdefore** [comment]
Thanks for spotting this @jmbreuer . Should be resolved now.
